name: "Hello World"
description: "Greet someone and record the time"

inputs:
  token_action:
    description: "The github access token"
    required: true
  warning_time:
    description: "the time duration which warning people"
    required: true
  type:
    description: "the type of message which need to send to robot"
    required: false
    default: "markdown"
  uri_warn:
    description: "the webhook_uri which corresponding to robot"
    required: true
  label_skip:
    description: "this action will skip check the issue which labeled label_skip"
    required: false
    default: ""
  label_check:
    description: "the label of issue which need to check"
    required: true
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node16"
  main: "src/index.js"
