name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token_action:  
    description: 'The github access token'
    required: true
    default: 'World'
  warning_days: 
    description: 'the time duration which warning people'
    required: false
    default: 0
  error_days:
    description: 'the time duration which error people'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'